name: drupal-9
recipe: drupal9
config:
  webroot: web
  php: '7.3'
  via: apache
  database: mysql
  xdebug: true
services:
  appserver:
    build:
      - composer install
    type: php
    config:
      php: config/php.ini
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://drupal-9.lndo.site"
