name: drupal-9
recipe: drupal9
config:
  webroot: web
  php: '7.4'
  via: apache
  xdebug: true
services:
  appserver:
    build:
      - composer install
    type: php
    config:
      php: lando.php.ini
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://drupal-9.lndo.site"
  memcache:
    type: memcached
    portforward: false
    mem: 128
  db:
    type: mariadb
    portforward: true
